version: '3.1'

services:

  mongo:
    build: /mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jump2digital
      MONGO_INITDB_ROOT_PASSWORD: "17112023"

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: jump2digital
      ME_CONFIG_MONGODB_ADMINPASSWORD: "17112023"
      ME_CONFIG_MONGODB_URL: mongodb://jump2digital:17112023@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: jump2digital
      ME_CONFIG_BASICAUTH_PASSWORD: "17112023"

  api:
     build: /API
     ports:
      - 17011:17011
     depends_on:
      - mongo
